import { afterEach,describe,expect,it } from 'vitest';
import { createApp } from '../server/app.mjs';
import { resolve } from 'node:path';
const servers=[];async function app(options){const server=await createApp(options);servers.push(server);return server;}
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>s.close()));});
describe('AI service boundaries',()=>{
  it('serves production files with cache headers without the AI rate limit',async()=>{const server=await app({env:{SERVE_STATIC:'true'},staticRoot:resolve('public')});const manifest=await server.inject('/manifest.webmanifest');expect(manifest.statusCode).toBe(200);expect(manifest.headers['cache-control']).toBe('no-cache');expect(manifest.headers['x-content-type-options']).toBe('nosniff');for(let i=0;i<35;i++)expect((await server.inject('/icon.svg')).statusCode).toBe(200);expect((await server.inject('/api/missing')).statusCode).toBe(404);});
  it('reports not configured without exposing secret values',async()=>{const server=await app({env:{}});const response=await server.inject('/api/status');expect(response.json()).toEqual({configured:false,cloudAuth:false,maxAudioMB:24});});
  it('rejects unauthenticated requests when local development is disabled',async()=>{const server=await app({env:{OPENAI_API_KEY:'test-key'}});const response=await server.inject({method:'POST',url:'/api/summarize',payload:{title:'Aula',transcript:'Uma orientação'}});expect(response.statusCode).toBe(401);});
  it('rejects hostile origins even when localhost development is enabled',async()=>{const server=await app({env:{ALLOW_LOCAL_AI:'true',OPENAI_API_KEY:'test-key'}});const response=await server.inject({method:'POST',url:'/api/summarize',headers:{host:'localhost:8787',origin:'https://untrusted.example'},payload:{title:'Aula',transcript:'Uma orientação'}});expect(response.statusCode).toBe(401);});
  it('returns an honest unavailable error with no API key',async()=>{const server=await app({env:{ALLOW_LOCAL_AI:'true'}});const response=await server.inject({method:'POST',url:'/api/summarize',headers:{host:'localhost:8787'},payload:{title:'Aula',transcript:'Uma orientação'}});expect(response.statusCode).toBe(503);});
  it('keeps only task evidence present in the transcript and derives timestamps',async()=>{const server=await app({env:{ALLOW_LOCAL_AI:'true',OPENAI_API_KEY:'test-key'},upstream:async()=>new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({summary:'Prática lenta.',tasks:[{title:'Estudar devagar',evidence:'Pratique devagar.',timestamp:999},{title:'Inventada',evidence:'Toque a 180 BPM.',timestamp:5}],questions:[]})}]}]}),{status:200,headers:{'Content-Type':'application/json'}})});const response=await server.inject({method:'POST',url:'/api/summarize',headers:{host:'localhost:8787'},payload:{title:'Aula',transcript:'[01:12] Pratique devagar.'}});expect(response.statusCode).toBe(200);expect(response.json().tasks).toEqual([{title:'Estudar devagar',evidence:'Pratique devagar.',timestamp:72}]);});
  it('validates the input before contacting the provider',async()=>{let called=false;const server=await app({env:{ALLOW_LOCAL_AI:'true',OPENAI_API_KEY:'test-key'},upstream:async()=>{called=true;throw new Error('unexpected');}});const response=await server.inject({method:'POST',url:'/api/summarize',headers:{host:'localhost:8787'},payload:{title:'Aula',transcript:'x'}});expect(response.statusCode).toBe(400);expect(called).toBe(false);});
});
