import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { ArrowLeft, Plus, Play, Pencil, MessageSquare, FileUp, Check, Trash2, Focus, CalendarDays } from 'lucide-react';
import { db, storeAsset } from '../db';
import { now, uid, hands, statuses, localDay, type Segment, type Region, type Hand } from '../domain';
import { Modal, Field, Empty, Badge, ErrorBox, errorText } from './common';
import { PieceForm } from './Library';
import ScoreViewer from './ScoreViewer';

export function SegmentForm({ pieceId, scoreId, region, segment, onClose, onSaved }: { pieceId:string; scoreId:string; region?:Region; segment?:Segment; onClose:()=>void; onSaved:(id:string)=>void }) {
  const [title,setTitle]=useState(segment?.title??''), [measures,setMeasures]=useState(segment?.measures??''), [goal,setGoal]=useState(segment?.goal??'');
  const [difficulty,setDifficulty]=useState(segment?.difficulty??'Ritmo'), [hand,setHand]=useState<Hand>(segment?.hand??'both'), [bpm,setBpm]=useState(segment?.bpm??60);
  const [review,setReview]=useState(segment?.reviewDate??''), [error,setError]=useState('');
  return <Modal title={segment?'Editar trecho':'Novo trecho de estudo'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{const id=segment?.id??uid();await db.segments.put({id,pieceId,scoreId,title:title.trim(),measures,goal,difficulty,hand,bpm,reviewDate:review,regions:segment?.regions??(region?[region]:[]),createdAt:segment?.createdAt??now(),rating:segment?.rating});onSaved(id);onClose();}catch(err){setError(errorText(err));}}}>
    <Field label="Nome do trecho"><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Entrada da mão esquerda" autoFocus/></Field>
    <div className="form-grid"><Field label="Compassos"><input value={measures} onChange={e=>setMeasures(e.target.value)} placeholder="Ex.: 17–24" maxLength={40}/></Field><Field label="O que precisa de atenção"><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['Ritmo','Leitura','Dedilhado','Articulação','Dinâmica','Pedal','Coordenação','Memória'].map(x=><option key={x}>{x}</option>)}</select></Field></div>
    <Field label="Objetivo / orientação"><textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={3} maxLength={3000} placeholder="O que você quer melhorar neste trecho?"/></Field>
    <div className="form-grid"><Field label="Mão"><select value={hand} onChange={e=>setHand(e.target.value as Hand)}>{Object.entries(hands).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="BPM inicial"><input type="number" min={20} max={300} required value={bpm} onChange={e=>setBpm(Number(e.target.value))}/></Field></div>
    <Field label="Revisar em (opcional)"><input type="date" value={review} onChange={e=>setReview(e.target.value)}/></Field><ErrorBox message={error}/><footer className="modal-actions"><button className="btn" disabled={!title.trim()}>Salvar trecho</button></footer>
  </form></Modal>;
}
export default function PieceDetail({ id, onBack, onPractice, notify }: { id:string;onBack:()=>void;onPractice:(segmentId:string)=>void;notify:(s:string)=>void }) {
  const piece=useLiveQuery(()=>db.pieces.get(id),[id]);
  const scores=useLiveQuery(()=>db.scores.where('pieceId').equals(id).toArray(),[id])??[];
  const segments=useLiveQuery(()=>db.segments.where('pieceId').equals(id).toArray(),[id])??[];
  const notes=useLiveQuery(()=>db.notes.where('pieceId').equals(id).toArray(),[id])??[];
  const tasks=useLiveQuery(()=>db.tasks.where('pieceId').equals(id).toArray(),[id])??[];
  const [scoreId,setScoreId]=useState(''), [tab,setTab]=useState('segments'), [edit,setEdit]=useState(false), [segmentForm,setSegmentForm]=useState<{region?:Region;segment?:Segment}|null>(null);
  const [target,setTarget]=useState<Region>(), [note,setNote]=useState(''), [source,setSource]=useState<'mine'|'teacher'>('teacher'), [task,setTask]=useState('');
  const active=scores.find(s=>s.id===scoreId)??scores[0];
  if(!piece)return <Empty title="Carregando peça" text="Preparando seu espaço de estudo."/>;
  return <><button className="back-link" onClick={onBack}><ArrowLeft size={17}/>Repertório</button><div className="page-heading compact"><div><Badge variant={piece.status}>{statuses[piece.status]}</Badge><h1>{piece.title}</h1><p>{piece.composer||'Seu repertório'}{piece.tags&&` · ${piece.tags}`}</p></div><button className="btn secondary" onClick={()=>setEdit(true)}><Pencil size={16}/>Editar peça</button></div>
  <div className="study-layout"><section className="score-card"><div className="section-heading"><div><FileUp size={18}/>{scores.length>0?<select aria-label="Versão da partitura" value={active?.id??''} onChange={e=>{setScoreId(e.target.value);setTarget(undefined);}}>{scores.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>:<h2>Partitura</h2>}</div><label className="btn small secondary file-button"><Plus size={16}/>Importar<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use PDF ou imagem.');let next='';await db.transaction('rw',[db.assets,db.scores],async()=>{const asset=await storeAsset(file);next=uid();await db.scores.add({id:next,pieceId:id,assetId:asset.id,title:file.name,createdAt:now()});});setScoreId(next);setTarget(undefined);notify('Partitura salva neste dispositivo.');}catch(err){notify(errorText(err));}e.target.value='';}}/></label></div>
  {active?<ScoreViewer key={active.id} score={active} notify={notify} targetRegion={target} onRegion={region=>setSegmentForm({region})}/>:<Empty title="Traga sua partitura" text="Importe um PDF ou uma imagem. Você poderá escrever sobre ela e marcar os trechos que quer praticar."/>}</section>
  <aside className="study-aside"><div className="tabs small-tabs">{[['segments','Trechos'],['notes','Notas'],['tasks','Tarefas']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</div>
  {tab==='segments'&&<><div className="aside-heading"><h2>Um trecho de cada vez</h2><button className="icon-btn" aria-label="Adicionar trecho" onClick={()=>setSegmentForm({})}><Plus size={20}/></button></div>{segments.length?segments.map(s=><article className="segment-card" key={s.id}><div className="row between"><Badge>{s.difficulty}</Badge><button className="icon-btn" aria-label={`Editar trecho ${s.title}`} onClick={()=>setSegmentForm({segment:s})}><Pencil size={15}/></button></div><h3>{s.title}</h3><p>{s.measures?`Compassos ${s.measures} · `:''}{hands[s.hand]}</p>{s.goal&&<p className="segment-goal">{s.goal}</p>}<div className="segment-meta"><strong>{s.bpm} <small>BPM</small></strong>{s.reviewDate&&<span className={s.reviewDate<=localDay()?'due':''}><CalendarDays size={14}/>{s.reviewDate.split('-').reverse().join('/')}</span>}</div><div className="row"><button className="btn small" onClick={()=>onPractice(s.id)}><Play size={15}/>Praticar</button>{s.regions.length>0&&<button className="btn small secondary" onClick={()=>{setScoreId(s.scoreId);setTarget({...s.regions[0]});}}><Focus size={15}/>Ver</button>}<button className="icon-btn subtle" aria-label={`Excluir trecho ${s.title}`} onClick={async()=>{if(!window.confirm(`Excluir o trecho “${s.title}”? A partitura e o histórico serão preservados.`))return;try{await db.transaction('rw',[db.segments,db.presets,db.tasks],async()=>{await db.segments.delete(s.id);await db.presets.where('segmentId').equals(s.id).delete();await db.tasks.where('segmentId').equals(s.id).modify({segmentId:undefined});});notify('Trecho excluído.');}catch(err){notify(errorText(err));}}}><Trash2 size={15}/></button></div></article>):<Empty title="Onde concentrar o estudo?" text="Marque uma região na partitura ou adicione um trecho pelo botão +."/>}</>}
  {tab==='notes'&&<><h2 className="aside-title">O que lembrar</h2><form className="note-form" onSubmit={async e=>{e.preventDefault();if(!note.trim())return;try{await db.notes.add({id:uid(),pieceId:id,text:note.trim(),source,createdAt:now()});setNote('');}catch(err){notify(errorText(err));}}}><Field label="Origem"><select value={source} onChange={e=>setSource(e.target.value as 'mine'|'teacher')}><option value="teacher">Orientação do professor, registrada por mim</option><option value="mine">Minha observação</option></select></Field><textarea aria-label="Nova observação" value={note} onChange={e=>setNote(e.target.value)} rows={4} maxLength={5000} placeholder="Dedilhado, interpretação, o que perguntar na próxima aula…"/><button className="btn small" disabled={!note.trim()}><Plus size={15}/>Salvar nota</button></form>{notes.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(n=><article className="note-card" key={n.id}><span><MessageSquare size={14}/>{n.source==='teacher'?'Orientação registrada':n.source==='ai'?'Sugestão da IA':'Minha nota'}</span><p>{n.text}</p><button className="icon-btn subtle" aria-label="Excluir observação" onClick={async()=>{if(window.confirm('Excluir esta observação?'))try{await db.notes.delete(n.id);}catch(err){notify(errorText(err));}}}><Trash2 size={14}/></button></article>)}</>}
  {tab==='tasks'&&<><h2 className="aside-title">Próximos passos</h2><form className="inline-form" onSubmit={async e=>{e.preventDefault();if(!task.trim())return;try{await db.tasks.add({id:uid(),pieceId:id,title:task.trim(),done:false,dueDate:'',createdAt:now()});setTask('');}catch(err){notify(errorText(err));}}}><input aria-label="Nova tarefa" value={task} maxLength={300} onChange={e=>setTask(e.target.value)} placeholder="O que praticar?"/><button className="icon-btn selected" disabled={!task.trim()} aria-label="Adicionar tarefa"><Plus size={19}/></button></form>{tasks.map(t=><div className="task-row" key={t.id}><button className={`check-button ${t.done?'checked':''}`} aria-label={`${t.done?'Reabrir':'Concluir'} ${t.title}`} onClick={async()=>{try{await db.tasks.update(t.id,{done:!t.done});}catch(err){notify(errorText(err));}}}>{t.done&&<Check size={14}/>}</button><span className={t.done?'done':''}>{t.title}</span><button className="icon-btn subtle" aria-label="Excluir tarefa" onClick={async()=>{if(window.confirm('Excluir esta tarefa?'))try{await db.tasks.delete(t.id);}catch(err){notify(errorText(err));}}}><Trash2 size={14}/></button></div>)}</>}
  </aside></div>
  {edit&&<PieceForm piece={piece} onClose={()=>setEdit(false)} onSaved={()=>notify('Peça atualizada.')}/>}
  {segmentForm&&<SegmentForm pieceId={id} scoreId={segmentForm.segment?.scoreId??active?.id??''} region={segmentForm.region} segment={segmentForm.segment} onClose={()=>setSegmentForm(null)} onSaved={()=>notify('Trecho salvo. Você já pode praticar.')}/>}
  </>;
}
